# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chirps', '0002_auto_20160323_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chirps', models.ManyToManyField(to='chirps.Chirp')),
            ],
        ),
    ]
