# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chirps', '0003_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chirp',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created'),
        ),
    ]
