# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-04 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chirps', '0005_auto_20160324_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='chirp',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
