# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-04 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chirps', '0006_chirp_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='chirp',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
